version: '3.3'
services:
  master:
    image: locust-grpc:latest
    command: -f /scripts/load_test_grpc_script.py --master -H http://master:8089
    ports:
      - "9001:8089"
    volumes:
      - ./scripts:/scripts
    tty: true

  worker:
    image: locust-grpc:latest
    command: -f /scripts/load_test_grpc_script.py --worker --master-host master
    volumes:
      - ./scripts:/scripts
    tty: true
    depends_on:
      - master

  api:
    image: test-grpc-python
    ports:
      - "50051:50051"
    environment:
      - MODEL_PATH=$MODEL_PATH
    tty: true