version: '3.3'
services:
  onnx_example_api:
    build:
      context: .
      args:
        S3_BUCKET: $S3_BUCKET
        S3_BUCKET_KEY: $S3_BUCKET_KEY
        MODEL_PATH: $MODEL_PATH
    volumes:
      - ./models:/models
    ports:
      - "80:80"