# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onnxGrpcServer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='onnxGrpcServer.proto',
  package='onnxserver',
  syntax='proto3',
  serialized_options=b'\n\007ex.grpc\242\002\003HSW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14onnxGrpcServer.proto\x12\nonnxserver\"|\n\tFloatData\x12\x0f\n\x07\x65ngines\x18\x01 \x01(\x02\x12\x1a\n\x12passenger_capacity\x18\x02 \x01(\x02\x12\x0c\n\x04\x63rew\x18\x03 \x01(\x02\x12\x16\n\x0e\x63ompany_rating\x18\x04 \x01(\x02\x12\x1c\n\x14review_scores_rating\x18\x05 \x01(\x02\"c\n\x0f\x43\x61tegoricalData\x12\x18\n\x10\x64_check_complete\x18\x01 \x01(\t\x12\x1f\n\x17moon_clearance_complete\x18\x02 \x01(\t\x12\x15\n\riata_approved\x18\x03 \x01(\t\"t\n\x08\x46\x65\x61tures\x12-\n\x0e\x66loat_features\x18\x01 \x01(\x0b\x32\x15.onnxserver.FloatData\x12\x39\n\x14\x63\x61tegorical_features\x18\x02 \x01(\x0b\x32\x1b.onnxserver.CategoricalData\"\x19\n\tPredicted\x12\x0c\n\x04prob\x18\x01 \x01(\x02\"\x1d\n\x0cUpdateParams\x12\r\n\x05param\x18\x01 \x01(\t\"\x17\n\x05Reply\x12\x0e\n\x06status\x18\x01 \x01(\t2\x93\x01\n\x15\x43TCVInferenceServicer\x12<\n\x07Predict\x12\x14.onnxserver.Features\x1a\x15.onnxserver.Predicted\"\x00(\x01\x30\x01\x12<\n\x0bUpdateModel\x12\x18.onnxserver.UpdateParams\x1a\x11.onnxserver.Reply\"\x00\x42\x0f\n\x07\x65x.grpc\xa2\x02\x03HSWb\x06proto3'
)




_FLOATDATA = _descriptor.Descriptor(
  name='FloatData',
  full_name='onnxserver.FloatData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='engines', full_name='onnxserver.FloatData.engines', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='passenger_capacity', full_name='onnxserver.FloatData.passenger_capacity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crew', full_name='onnxserver.FloatData.crew', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='company_rating', full_name='onnxserver.FloatData.company_rating', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='review_scores_rating', full_name='onnxserver.FloatData.review_scores_rating', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=160,
)


_CATEGORICALDATA = _descriptor.Descriptor(
  name='CategoricalData',
  full_name='onnxserver.CategoricalData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='d_check_complete', full_name='onnxserver.CategoricalData.d_check_complete', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='moon_clearance_complete', full_name='onnxserver.CategoricalData.moon_clearance_complete', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iata_approved', full_name='onnxserver.CategoricalData.iata_approved', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=261,
)


_FEATURES = _descriptor.Descriptor(
  name='Features',
  full_name='onnxserver.Features',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='float_features', full_name='onnxserver.Features.float_features', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='categorical_features', full_name='onnxserver.Features.categorical_features', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=379,
)


_PREDICTED = _descriptor.Descriptor(
  name='Predicted',
  full_name='onnxserver.Predicted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prob', full_name='onnxserver.Predicted.prob', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=406,
)


_UPDATEPARAMS = _descriptor.Descriptor(
  name='UpdateParams',
  full_name='onnxserver.UpdateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='param', full_name='onnxserver.UpdateParams.param', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=437,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='onnxserver.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='onnxserver.Reply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=462,
)

_FEATURES.fields_by_name['float_features'].message_type = _FLOATDATA
_FEATURES.fields_by_name['categorical_features'].message_type = _CATEGORICALDATA
DESCRIPTOR.message_types_by_name['FloatData'] = _FLOATDATA
DESCRIPTOR.message_types_by_name['CategoricalData'] = _CATEGORICALDATA
DESCRIPTOR.message_types_by_name['Features'] = _FEATURES
DESCRIPTOR.message_types_by_name['Predicted'] = _PREDICTED
DESCRIPTOR.message_types_by_name['UpdateParams'] = _UPDATEPARAMS
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FloatData = _reflection.GeneratedProtocolMessageType('FloatData', (_message.Message,), {
  'DESCRIPTOR' : _FLOATDATA,
  '__module__' : 'onnxGrpcServer_pb2'
  # @@protoc_insertion_point(class_scope:onnxserver.FloatData)
  })
_sym_db.RegisterMessage(FloatData)

CategoricalData = _reflection.GeneratedProtocolMessageType('CategoricalData', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORICALDATA,
  '__module__' : 'onnxGrpcServer_pb2'
  # @@protoc_insertion_point(class_scope:onnxserver.CategoricalData)
  })
_sym_db.RegisterMessage(CategoricalData)

Features = _reflection.GeneratedProtocolMessageType('Features', (_message.Message,), {
  'DESCRIPTOR' : _FEATURES,
  '__module__' : 'onnxGrpcServer_pb2'
  # @@protoc_insertion_point(class_scope:onnxserver.Features)
  })
_sym_db.RegisterMessage(Features)

Predicted = _reflection.GeneratedProtocolMessageType('Predicted', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTED,
  '__module__' : 'onnxGrpcServer_pb2'
  # @@protoc_insertion_point(class_scope:onnxserver.Predicted)
  })
_sym_db.RegisterMessage(Predicted)

UpdateParams = _reflection.GeneratedProtocolMessageType('UpdateParams', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPARAMS,
  '__module__' : 'onnxGrpcServer_pb2'
  # @@protoc_insertion_point(class_scope:onnxserver.UpdateParams)
  })
_sym_db.RegisterMessage(UpdateParams)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'onnxGrpcServer_pb2'
  # @@protoc_insertion_point(class_scope:onnxserver.Reply)
  })
_sym_db.RegisterMessage(Reply)


DESCRIPTOR._options = None

_CTCVINFERENCESERVICER = _descriptor.ServiceDescriptor(
  name='CTCVInferenceServicer',
  full_name='onnxserver.CTCVInferenceServicer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=465,
  serialized_end=612,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='onnxserver.CTCVInferenceServicer.Predict',
    index=0,
    containing_service=None,
    input_type=_FEATURES,
    output_type=_PREDICTED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateModel',
    full_name='onnxserver.CTCVInferenceServicer.UpdateModel',
    index=1,
    containing_service=None,
    input_type=_UPDATEPARAMS,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CTCVINFERENCESERVICER)

DESCRIPTOR.services_by_name['CTCVInferenceServicer'] = _CTCVINFERENCESERVICER

# @@protoc_insertion_point(module_scope)
