# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import onnxGrpcServer_pb2 as onnxGrpcServer__pb2


class CTCVInferenceServicerStub(object):
    """Service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.stream_stream(
                '/onnxserver.CTCVInferenceServicer/Predict',
                request_serializer=onnxGrpcServer__pb2.Features.SerializeToString,
                response_deserializer=onnxGrpcServer__pb2.Predicted.FromString,
                )
        self.UpdateModel = channel.unary_unary(
                '/onnxserver.CTCVInferenceServicer/UpdateModel',
                request_serializer=onnxGrpcServer__pb2.UpdateParams.SerializeToString,
                response_deserializer=onnxGrpcServer__pb2.Reply.FromString,
                )


class CTCVInferenceServicerServicer(object):
    """Service definition.
    """

    def Predict(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CTCVInferenceServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.stream_stream_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=onnxGrpcServer__pb2.Features.FromString,
                    response_serializer=onnxGrpcServer__pb2.Predicted.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=onnxGrpcServer__pb2.UpdateParams.FromString,
                    response_serializer=onnxGrpcServer__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onnxserver.CTCVInferenceServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CTCVInferenceServicer(object):
    """Service definition.
    """

    @staticmethod
    def Predict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/onnxserver.CTCVInferenceServicer/Predict',
            onnxGrpcServer__pb2.Features.SerializeToString,
            onnxGrpcServer__pb2.Predicted.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/onnxserver.CTCVInferenceServicer/UpdateModel',
            onnxGrpcServer__pb2.UpdateParams.SerializeToString,
            onnxGrpcServer__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
