version: '3.3'
services:
  onnx_example_cpp_api:
    container_name: grcp_cpp_server_onnx_example_api
    # image: grcp_cpp_base:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile.ecs
    #   args:
    #     MODEL_PATH: $MODEL_PATH
    image: test-grpc-cpp
    # volumes:
    #   - ./models:/models
    ports:
      - "50051:50051"
    environment:
      - MODEL_PATH=$MODEL_PATH
    tty: true